[build]
target = "tbpfv3-tos-tos"

[target.tbpfv3-tos-tos]
rustflags = [
    "-C", "panic=abort",
    "-C", "overflow-checks=off",
]

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]
