[package]
name = "vrf-random"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# Keep this example independent from the parent workspace

[dependencies]
tako-sdk.workspace = true

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = true
