[package]
name = "aave-v3-pool"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tako-sdk.workspace = true
tako-macros.workspace = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
